### ISSUE TITLE
[Tri] Jouer la situation Tri

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro#213]
- [x] Affiche une situation vide #251 
- [x] Avoir le fond de de la situation #263 
- [x] Avoir une vraie consigne #264 
- [x] Avoir des friandises sur le plateau #265
- [x] Précharger les bonbons #279 
- [x] Les pièces connaissent leur dimensions #283 
- [x] Pouvoir sélectionner les pièces #281 
- [x] Pouvoir déplacer les friandises dans les contenants #284 
- [x] Avoir la logique des bacs #287 
- [x] Prendre en compte les friandises qui sont bien placées #290
- [x] Remettre les friandises mal placées sur le plateau #290
- [x] Afficher la fin avec le résultat #293 
- [x] Afficher le chrono #301 
- [x] Jouer les sons en cas de bon ou de mauvais placement #300 
- [x] Envoyer les événements au serveur
  - [x] Démarrage #294
  - [x] Bonbon trié #299 
  - [x] Bonbon mal trié #299
