### ISSUE TITLE
Intégration page d'accueil avec le dessin du parc

### ISSUE THREAD

**Issue by francois2metz** [betagouv/competences-pro#305]
- [x] Intégrer l'image #312 
- [x] Mettre un écran de chargement
- [x] Effet de survol propre
- [x] ~~[Dette]Positionner les zones cliquables en pourcentage~~
- [x] Saisie du nom en overlay sur l'accueil #341 
- [x] Mettre le nouveau fond avec les nouveaux batiments #342
- [x] Afficher la progression de l'évalué·e dans le parc #349
- [ ] ***En cours*** Afficher la progression de l'évalué·e en haut #367 
- [x] Désactiver les situations non accessible #357 
- [x] Déconnexion de l'évalué·e #344 
- [x] Bords arrondis sur l'accueil #343 
- [x] Nouvelle POLICE :police_car: #346 
- [x] Afficher le chemin derrière les personnages et le panneau d'accueil #356

**Comment by etienneCharignon** [comment]
Avec @morissetcl nous avons fait le positionnement en pourcentage puis nous avons renoncé car le résultat était plus compliqué (plus difficile à maintenir) et les pourcentages n'apportaient aucune flexibilité supplémentaire, la `<div class="situations"…` aillant une hauteur fixe (lui mettre un pourcentage ne marche pas ou alors il faudrait faire des choses encore plus compliquées).
